baseURL = "https://thisisabhinay.com/"
languageCode = "en-us"
title = "Abhinay's site"
theme= "hello-friend-ng"
paginate = 10

PygmentsCodeFences = true
PygmentsStyle = "monokai"


[author]
    name = "Abhinay Thakur"

[params]
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"

    # Subtitle for home
    homeSubtitle = "Frontend Engineer / Designer. Trying to reinvent art and storytelling in digital space."

    # Set disableReadOtherPosts to true in order to hide the links to other posts.
    disableReadOtherPosts = false

    # Enable sharing buttons, if you like
    enableSharingButtons = true
    
    # Dark mode toggle.
    enableThemeToggle = true

    # Metadata mostly used in document's head
    description = "Personal website and portfolio of Abhinay Thakur"
    keywords = "homepage, personal website, blog, portfolio, frontend, design, contact me"
    images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"


[languages]
    [languages.en]
        title = "Hello 👋, I'm Abhinay"
        # subtitle = "A simple theme for Hugo"
        # keywords = "personal website, blog, portfolio, frontend, design, contact me"
        copyright = "All rights reserved."
        readOtherPosts = "Read other posts"

        [languages.en.params.logo]
            logoText = "$ cd /home/"
            logoHomeLink = "/"
        # or
        #
        # path = "/img/your-example-logo.svg"
        # alt = "Your example logo alt text"

# And you can even create generic menu
[[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
    weight     = 10

[[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
    weight     = 40

[[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects"
    weight     = 30

[[menu.main]]
    identifier = "work"
    name       = "Work"
    url        = "/work"
    weight     = 20

[[params.social]]
    name       = "twitter"
    url        = "https://www.twitter.com/thisisabhinay"
    weight     = 10

[[params.social]]
    name       = "linkedin"
    url        = "https://www.linkedin.com/in/thisisabhinay"
    weight     = 10

[[params.social]]
    name       = "polywork"
    url        = "https://www.polywork.com/thisisabhinay"
    weight     = 10

[[params.social]]
    name       = "github"
    url        = "https://www.github.com/thisisabhinay"
    weight     = 10

[[params.social]]
    name       = "email"
    url        = "mailto:a8h1nay@gmail.com"
    weight     = 10

[params.footer]
    trademark = true
    rss = true
    copyright = true
    author = true

    topText = []
    bottomText = []